### ISSUE TITLE
Mobile does not look good.  Must fix.

### ISSUE THREAD

**Issue by monroemann** [monroemann/breakdivingnew#117]
Look at the site on mobile.  Homepage looks fine.  All others look terrible.  For some reason, the items are not stacking as they should.

**Comment by Mist12345** [comment]
Hi, I realize this has already been assigned to people but I also noticed the help wanted tag was still there. If you're still looking for the help I would be happy to lend a hand.

**Comment by monroemann** [comment]
Hello!

Thanks for your interest in helping!

But I’m sorry: who is this?  Are you someone from Firehose?

-Monroe
