### ISSUE TITLE
Is there a way to create a one-time Slack link?

### ISSUE THREAD

**Issue by monroemann** [monroemann/breakdivingnew#208]
Right now, every month, to update the Slack link, I have to actually replace in over 50 places on over 50 pages.  It's difficult, and sometimes, I miss a page.

Is there a way to use jquery or something so that we only have to update the Slack link in ONE place each month, and it automatically updates ALL of the places where we have the slack link?  

Thanks,-Monroe

**Comment by monroemann** [comment]
Like just now, wow, I updated all links, but forgot the nav bar, because it had an even OLDER slack link, so in my 'search and replace' it didn't show up.  This is a huge problem that we need to fix.

**Comment by taratip** [comment]
I think it can be done using jquery to update the slack link.
