### ISSUE TITLE
Add a 'free consultation' form on the website

### ISSUE THREAD

**Issue by monroemann** [monroemann/breakdivingnew#24]

**Comment by chmb** [comment]
Which page would you like this placed? Also is there a particular email you want the entries to be sent?

**Comment by monroemann** [comment]
Where to place it? That’s a good question. Perhaps on the “coaching” page? Or maybe on the “Programs” drop down?  I’m not quite sure yet.  Maybe in multiple places?

I think the form should come to: info@breakdiving.org

BUT wait—we may be able to set up a form in saleforce that links into sales force. 

This may be something to wait a few days on...
