### ISSUE TITLE
Determine a way to integrate latest wordpress blog posts onto the website

### ISSUE THREAD

**Issue by monroemann** [monroemann/breakdivingnew#32]

**Comment by taratip** [comment]
I did some research regarding this. It seems we can install WordPress in web hosting (I believe we currently use GoDaddy for web hosting) then create some php script to display the latest posts to a web page.

**Comment by monroemann** [comment]
Yes I think the key is PHP. We’d have to learn how to write that script in PHP... :)

**Comment by monroemann** [comment]
I found a new volunteer who apparently knows some PHP.  That may help :D
