### ISSUE TITLE
URGENT: Putting a huge table onto a webpage

### ISSUE THREAD

**Issue by monroemann** [monroemann/breakdivingnew#60]
I have the full list of 'dives' for the dive program.  Over 140 rows, and about 8 columns.  It would be a pain in the butt to copy and paste each cell.  

Is there a way to copy and paste the entire table on the 'Dive Program List'?

Or, does it make more sense to turn the file into a PDF, and have it be downloadable to people who visit the site?

**Comment by taratip** [comment]
What format of file it is? Is it Excel?

**Comment by monroemann** [comment]
Right now, it’s a Word table.

**Comment by taratip** [comment]
Can you send me the file? I'll see what I can do.

**Comment by monroemann** [comment]
Done!  Fantastic work Tara!
