### ISSUE TITLE
Nav bar still having problems with paypal button

### ISSUE THREAD

**Issue by monroemann** [monroemann/breakdivingnew#72]
See screenshot:

https://gyazo.com/af44908dba9f2924eec2d797aff1c6dd

Maybe it's because there are so many nav items?  If we could reduce the spacing slightly between each of the nav items, that might fix this...

Thoughts?
-Monroe

**Comment by taratip** [comment]
Could we group volunteer and job together? so that we'll have some space for the paypal button

**Comment by monroemann** [comment]
Yes!  Great idea.  We don't have any jobs now anyway to offer :D  Also, once we have money, I prefer to hire first those (like you, and others) who have already donated tens and tens of hours to helping the company.  So maybe there shouldn't even be a 'jobs' section anyway!  Perfect!

SO: Can you please take the text from 'jobs' and add it as a separate section on the 'volunteer' page?  And then delete the 'jobs' page.  No longer needed. :D   Very smart Tara!

**Comment by monroemann** [comment]
Done!
