### ISSUE TITLE
Create Fluency Project testimonial section and add these

### ISSUE THREAD

**Issue by monroemann** [monroemann/breakdivingnew#84]
“ Very intensive and effective way of studying and practicing! I will be back for more. ”

“ YO! Had a great time this afternoon! Monroe, Paris, Brandon, Michelle, nice meeting y'all, and I can't wait to witness the growing of this group! P.S. SURPRISE: Monroe's gonna organizing book club events in the coming weeks, so stay tuned & COME TO THE EVENTS! It'll be FUN! ”

“ Unlike the other Fluency Project meetups, fluency is not a requirement for the Mandarin group which is great for me! I took a year of Mandarin in college and have had little exposure since then. Monroe was extremely patient as we worked through basic conversations and a writing exercise. I was surprised how much Mandarin I remembered when forced to speak. His incorporation of writing exercises makes it feel like I'm actually learning Mandarin. True to his description, Monroe is a excellent organizer and was able to talk down to my level as well as provide resources to help me along. After watching me struggle with Chinese, we flipped the tables and spoke French for the next hour over coffee. All in all, this is a great set up for people with basic proficiency looking to get all the way to fluent. ”

“ This group made me sit down and WORK-- super appreciated because there's just no other way! I really like the format because it exposed me to native French via the audio portion, in a normal pace so that we were not babied by a teacher-style slow 
clear pronunciation. Also getting all the time to speak made me recognize the holes in my vocabulary that I could look up later. Starting with conjugating a verb in full is a smart warm-up that sets the pace. Very focused, efficient, and effective. I also liked that in the Italian one, reading from novels introduced advanced and more poetic vocab. Basically I've never seen such a good level of pushing advanced vocab and contextual constructs. ”

“ The first meeting was fun and productive, it forced me to speak Italian. That is what I wanted even though hesitant to make a fool of myself. Everyone was supportive and the atmosphere was friendly and noncompetitive. You should join us!

**Comment by monroemann** [comment]
Chomba, since you are working on the other testimonials, perhaps you can work on this one too! 

Thank you!

**Comment by chmb** [comment]
Done!
