### ISSUE TITLE
Add these testimonials under a section called Break Diving Meetings

### ISSUE THREAD

**Issue by monroemann** [monroemann/breakdivingnew#86]
“ I loved the people in this group. Everyone really wanted to focus on getting a plan and moving forward. ”
“ I'm excited about [having] attended the 1st Break Divers meeting. It was a gorgeous day at Bryant Park and I enjoyed meeting new 'break divers' and learning their stories. It was great to get fresh perspectives on an area I have been struggling for a long time. It was reinforcing to know that we are not alone in the struggle with fears, emotions, self-doubt, indecision and procrastination. Change becomes maneageable with a good support system. I'm curious to see where this goes. 2nd Meetup @ Coney Island: Had a great time at the beach.  Thank you for the awesome and terrifying ride on the cyclone. The pictures came out great. I appreciated the career advice, taking the next steps, and your perspectives on self-publishing. It was nice to get to know you better as well. :) ”

**Comment by chmb** [comment]
Do you think this would fit better on the current testimonials page?

**Comment by monroemann** [comment]
Yes, that is what I was trying to say.  I see now I was unclear.  What I meant: Create a new section in the testimonials section, called "Break Diving Meetings" and then place these in that section.

**Comment by chmb** [comment]
Done!
