### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by monroemann** [monroemann/breakdivingnew#95]
1. Sometimes, I make a mistake, and start making edits without switching off the old branch that I already uploaded to GitHub.  When this happens, is there a way to take the new changes and move them to a new branch, or is it too late?

2. Tara, I noticed that you created a separate file for the nav, and another for the footer.  How does the website know to merge them all?  I'm very curious.

**Comment by taratip** [comment]
1. I think you can just continue making changes in the old branch and type `git push origin old-branch-name:new-branch-name` when push to github. It will create another branch with new name you specify.

2. I include the following:
```  
<script>
    $(function(){
      $("#nav-placeholder").load("navigation.html");
    });
  </script>
```
and 
```
<script>
    $(function(){
      $("#footer-placeholder").load("footer.html");
    });
  </script>
```
in every files to load navigation menu and footer

Note: When merging, can you delete old branches too? Currently, we have a few branches that left over after merged.

**Comment by monroemann** [comment]
I see. We are using jQuery to import the Mac and the footer. How does it know where to put them?

Related issue: all the google landing pages currently have the old navbar and do not have the footer. This means that visitors from Google AdWords don’t see the new nav or footer. 

How to change? Do we remove the nav bar on each of those pages and then add that jQuery that you created?  And then it will automatically do the merge?

Finally, do you mean that I should delete the branches on Github?  I wasn’t sure if I should—was worried I might break something.

**Comment by taratip** [comment]
It puts at where we specify the DOM id. For example, we put `<div id="footer-placeholder></div>` at any place on the page and the script 
```
$(function(){
      $("#footer-placeholder").load("footer.html");
 });
``` 
will put footer.html at the place with id `footer-placeholder`

Correct. The google landing pages will not see the new nav or footer unless you include them in the pages and delete the old navbar.

You can leave the branches as they are if you don't want to delete.

**Comment by monroemann** [comment]
Thanks for the tutorial!  I see now how useful it is to use jquery.

Idea: Right now, when I reset the slack link every month, I have to do so on about 30 pages.  Could we use jquery to create a page called 'slack_link.html' and have the load wherever we have  $("#slack-link-placeholder").load("slack_link.html")   ??

If so, it would save me a LOT of time every month, plus, it would ensure I don't miss any page that requires an updated slack link.  Possible?
